package com.agrilink.notification;

public enum NotificationType {
    ORDER_CREATED,
    ORDER_ACCEPTED,
    ORDER_REJECTED,
    ORDER_CANCELLED,
    ORDER_EXPIRED,
    PAYMENT_HELD,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    ORDER_READY_FOR_PICKUP,
    DELIVERY_ASSIGNED,
    DELIVERY_PICKED_UP,
    DELIVERY_IN_TRANSIT,
    DELIVERY_DELIVERED,
    ORDER_COMPLETED,
    PAYOUT_RELEASED,
    DISPUTE_OPENED,
    DISPUTE_UPDATED,
    DISPUTE_RESOLVED,
    VERIFICATION_APPROVED,
    VERIFICATION_REJECTED,
    VERIFICATION_INFO_NEEDED,
    RATING_RECEIVED,
    SYSTEM
}
